eBottle: yarp::os::eValue Class Reference
yarp::os::eValue Class Reference
Single efficient Value class.
#include <eBottle.h>
Public Types
enum ValueType {
INT = 1, DOUBLE, CHARP, BOTTLE,
STRING
}
Basic types allowed in data transmission.
Public Member Functions
eValue ()
Default constructor.
eValue (const int i)
Integer eValue constructor.
eValue (const double d)
Double eValue constructor.
eValue (const char *p, const unsigned int size_p)
Blob eValue constructor.
eValue (const eBottle *p)
List eValue constructor.
eValue (const char *text)
String eValue constructor.
eValue (const std::string &s)
String eValue constructor.
~eValue ()
Class destructor.
eValue & operator= (const eValue &p)
ValueType getType () const
unsigned int getSize () const
bool isInt () const
bool isDouble () const
bool isBlob () const
bool isList () const
bool isString () const
int asInt () const
int * asIntPtr ()
int * asIntPtr () const
double asDouble () const
double * asDoublePtr ()
double * asDoublePtr () const
char * asBlob ()
char * asBlob () const
unsigned int asBlobLength () const
eBottle * asList ()
eBottle * asList () const
ConstString asString () const
std::string * asStringPtr ()
Static Public Member Functions
static eValue * makeBlob (const char *p, const unsigned int size)
blob type eValue factory
Detailed Description
Single efficient Value class.
This class replaces the behaviour and functionality of the Value YARP class. It is the base class that allows simple data transmission. To transmit more complex data, list eValues can be used.
Member Enumeration Documentation
enum yarp::os::eValue::ValueType
Basic types allowed in data transmission.
These are the simple value types that can be transmitted
Enumerator:
INT Integer data.
DOUBLE Double precission floating point data.
CHARP Blob of bytes.
BOTTLE List of eValues.
STRING String of characters.
Constructor & Destructor Documentation
eValue::eValue ()
Default constructor.
Creates an empty eValue
Referenced by makeBlob().
eValue::eValue (const int i)
Integer eValue constructor.
Creates an eValue with an integer
Parameters:
[in] i The integer to store
References INT.
eValue::eValue (const double d)
Double eValue constructor.
Creates an eValue with a double
Parameters:
[in] d The double to store
References DOUBLE.
eValue::eValue (const char * p, const unsigned int size_p)
Blob eValue constructor.
Creates an eValue with a blob of bytes. It Reserves its own memory and makes a copy of the blob.
Parameters:
[in] p A pointer to the memory to store
[in] size_p The size of the memory blob in bytes
References CHARP.
eValue::eValue (const eBottle * p)
List eValue constructor.
Creates an eValue with a list. The eValue do not copy the eBottle before storing it.
Parameters:
[in] p The pointer to the list to store
References BOTTLE.
eValue::eValue (const char * text)
String eValue constructor.
Creates an eValue with a string, making a copy of the char array.
Parameters:
[in] text The pointer to the null teminated string to store
References STRING.
eValue::eValue (const std::string & s)
String eValue constructor.
Creates an eValue with a string. It stores a copy of the string given.
Parameters:
[in] s The string to store
References STRING.
eValue::~eValue ()
Class destructor.
Frees all the memory used
References BOTTLE, CHARP, DOUBLE, INT, and STRING.
Member Function Documentation
eValue * eValue::makeBlob (const char * p, const unsigned int size) [static]
blob type eValue factory
Creates a dynamically allocated eValue with a blob inside. The blob is copied before stored.
Parameters:
[in] p A pointer to the memory to store
[in] size The size of the memory blob in bytes
Returns:
A pointer to the new eValue
References eValue().
eValue & eValue::operator= (const eValue & p)
Assignation operator
Parameters:
p The source eValue to copy
References asBlob(), asDouble(), asInt(), asList(), asString(), BOTTLE, CHARP, DOUBLE, getSize(), getType(), INT, and STRING.
eValue::ValueType eValue::getType () const
Access to eValue type
Returns:
The type of the data in the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
unsigned int eValue::getSize () const
Access to eValue size
Returns:
The size of the data in the eValue in bytes
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
bool eValue::isInt () const
Checks wheather the eValue holds a integer or not
Returns:
True if the eValue type is eValue::INT. Otherwise, false.
References INT.
bool eValue::isDouble () const
Checks wheather the eValue holds a double or not
Returns:
True if the eValue type is eValue::DOUBLE. Otherwise, false.
References DOUBLE.
bool eValue::isBlob () const
Checks wheather the eValue holds a blob or not
Returns:
True if the eValue type is eValue::CHARP. Otherwise, false.
References CHARP.
bool eValue::isList () const
Checks wheather the eValue holds a list or not
Returns:
True if the eValue type is eValue::BOTTLE. Otherwise, false.
References BOTTLE.
bool eValue::isString () const
Checks wheather the eValue holds a string or not
Returns:
True if the eValue type is eValue::STRING. Otherwise, false.
References STRING.
int eValue::asInt () const
Access to the eValue data as an integer
Returns:
A copy of the integer stored in the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
int * eValue::asIntPtr ()
Access to the eValue data as an integer
Returns:
A pointer to the integer inside the eValue
int * eValue::asIntPtr () const
Access to the eValue data as an integer
Returns:
A constant pointer to the integer inside the eValue
double eValue::asDouble () const
Access to the eValue data as an double
Returns:
A copy of the double stored in the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
double * eValue::asDoublePtr ()
Access to the eValue data as an double
Returns:
A pointer to the double inside the eValue
double * eValue::asDoublePtr () const
Access to the eValue data as an double
Returns:
A constant pointer to the double inside the eValue
char * eValue::asBlob ()
Access to the eValue data as an blob
Returns:
A pointer to the blob inside the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
char * eValue::asBlob () const
Access to the eValue data as an blob
Returns:
A constant pointer to the blob inside the eValue
unsigned int eValue::asBlobLength () const
Access to the eValue data size as a blob
Returns:
The size of the blob inside the eValue in bytes
eBottle * eValue::asList ()
Access to the eValue data as a list
Returns:
A pointer to the list inside the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
eBottle * eValue::asList () const
Access to the eValue data as a list
Returns:
A constant pointer to the list inside the eValue
yarp::os::ConstString eValue::asString () const
Access to the eValue data as a string
Returns:
A copy of the string stored in the eValue
Referenced by yarp::os::eBottle::copy(), yarp::os::eBottle::operator=(), and operator=().
std::string * eValue::asStringPtr ()
Access to the eValue data as a string
Returns:
A pointer to the string inside the eValue
The documentation for this class was generated from the following files:
eBottle.h
eBottle.cc