eBottle: yarp::os::eBottle Class Reference
yarp::os::eBottle Class Reference
Efficient eValue list class.
#include <eBottle.h>
Public Member Functions
eBottle ()
Default constructor.
eBottle (const char *txt)
String contructor.
eBottle (const std::string &s)
String contructor.
eBottle (const ConstString &s)
String contructor.
eBottle (const eBottle &eb)
Copy constructor.
virtual ~eBottle ()
Class destructor.
void copy (const eBottle *p)
Copy function.
eBottle & operator= (const eBottle &p)
Assignation operator.
virtual void clear ()
void add (const eValue *e)
void add (const eValue &e)
void addInt (const int i)
void addDouble (const double d)
void addBlob (const char *q, const unsigned int size)
void addString (const std::string &s)
void addString (const ConstString &s)
void addString (const char *s)
eBottle & addList ()
eBottle * addListPtr ()
void insert (const eValue *p, const unsigned int i)
void append (const eBottle &yb)
void remove (const unsigned int i)
unsigned int count () const
unsigned int size () const
eValue & operator[] (const unsigned int i)
eValue & operator[] (const unsigned int i) const
eValue & get (const unsigned int i)
eValue & get (const unsigned int i) const
eValue * getPtr (const unsigned int i) const
eValue * getPtr (const unsigned int i)
std::string toString () const
void fromString (const char *s)
void fromString (const std::string &s)
void fromString (const ConstString &s)
void fromBinary (const char *p, const int size)
const char *const toBinary (int *size) const
void toBinary (char *p) const
unsigned int getBinarySize () const
virtual bool read (ConnectionReader &connection)
virtual bool write (ConnectionWriter &connection)
Detailed Description
Efficient eValue list class.
This class is able to store an ordered list of eValues of different types, including nested lists, and to transmit it using YARP.
The main difference between this implementation and the YARP default one is that this is not strictly human readable, which permits a faster and more efficient memory copy and yarp transmission.
Furthermore, using the efficient copy operator, most of the memory leaks that pointers may cause are avoided.
Constructor & Destructor Documentation
eBottle::eBottle ()
Default constructor.
Creates an empty eBottle.
Referenced by addList(), and addListPtr().
eBottle::eBottle (const char * txt)
String contructor.
Creates an eBottle from a human readable string (in the same way YARP does).
Parameters:
txt A pointer to the null terminated char array
References fromString().
eBottle::eBottle (const std::string & s)
String contructor.
Creates an eBottle from a human readable string (in the same way YARP does).
Parameters:
s The string that represents the eBottle
References fromString().
eBottle::eBottle (const ConstString & s)
String contructor.
Creates an eBottle from a human readable string (in the same way YARP does).
Parameters:
s The string that represents the eBottle
References fromString().
eBottle::eBottle (const eBottle & eb)
Copy constructor.
Creates an eBottle as a copy of another one
Parameters:
[in] eb The source eBottle to copy
References copy().
eBottle::~eBottle () [virtual]
Class destructor.
Frees al the memory used in the object.
Member Function Documentation
void eBottle::copy (const eBottle * p)
Copy function.
Rebuilds the eBottle as a copy of another one
Parameters:
[in] p A pointer to the eBottle to copy from.
References addBlob(), addDouble(), addInt(), addListPtr(), addString(), yarp::os::eValue::asBlob(), yarp::os::eValue::asDouble(), yarp::os::eValue::asInt(), yarp::os::eValue::asList(), yarp::os::eValue::asString(), yarp::os::eValue::BOTTLE, yarp::os::eValue::CHARP, clear(), copy(), count(), yarp::os::eValue::DOUBLE, getPtr(), yarp::os::eValue::getSize(), yarp::os::eValue::getType(), yarp::os::eValue::INT, and yarp::os::eValue::STRING.
Referenced by copy(), and eBottle().
eBottle & eBottle::operator= (const eBottle & p)
Assignation operator.
Rebuilds the eBottle as a copy of another one
Parameters:
[in] p A reference to the eBottle to copy from.
References addBlob(), addDouble(), addInt(), addListPtr(), addString(), yarp::os::eValue::asBlob(), yarp::os::eValue::asDouble(), yarp::os::eValue::asInt(), yarp::os::eValue::asList(), yarp::os::eValue::asString(), yarp::os::eValue::BOTTLE, yarp::os::eValue::CHARP, clear(), yarp::os::eValue::DOUBLE, getPtr(), yarp::os::eValue::getSize(), yarp::os::eValue::getType(), yarp::os::eValue::INT, yarp::os::eValue::STRING, and values.
void eBottle::clear () [virtual]
Removes all the eValues inside the eBottle.
Referenced by copy(), operator=(), and read().
void eBottle::add (const eValue * e)
Inserts a copy of the an eValue at the end of the eBottle
Parameters:
[in] e A pointer to the eValue to insert
void eBottle::add (const eValue & e)
Inserts a copy of the an eValue at the end of the eBottle
Parameters:
[in] e A reference to the eValue to insert
void eBottle::addInt (const int i)
Inserts an integer type eValue at the end of the eBottle
Parameters:
[in] i The integer to insert
Referenced by copy(), and operator=().
void eBottle::addDouble (const double d)
Inserts a double type eValue at the end of the eBottle
Parameters:
[in] d The double to insert
Referenced by copy(), and operator=().
void eBottle::addBlob (const char * q, const unsigned int size)
Inserts a blob type eValue at the end of the eBottle, making first a local copy of the memory
Parameters:
[in] q A pointer to the blob
[in] size The size of the blob in bytes
Referenced by copy(), and operator=().
void eBottle::addString (const std::string & s)
Inserts a string eValue at the end of the eBottle
Parameters:
[in] s The string to insert
Referenced by copy(), and operator=().
void eBottle::addString (const ConstString & s)
Inserts a string eValue at the end of the eBottle
Parameters:
[in] s The string to insert
void eBottle::addString (const char * s)
Inserts a string eValue at the end of the eBottle, making first a copy local memory
Parameters:
[in] s A pointer to the null terminated char array to insert
eBottle & eBottle::addList ()
Reserves the memory for inserting a list at the end of the eBottle
Returns:
A reference to the empty list inserted in the eBottle
References eBottle().
eBottle * eBottle::addListPtr ()
Reserves the memory for inserting a list at the end of the eBottle
Returns:
A pointer to the empty list inserted in the eBottle
References eBottle().
Referenced by copy(), and operator=().
void eBottle::insert (const eValue * p, const unsigned int i)
Inserts a copy of an eValue into the eBottle at a given position
Parameters:
[in] p A pointer to the eValue to insert
[in] i The position where the eValue will be inserted
void eBottle::append (const eBottle & yb)
Inserts all the values inside a given eBottle at the end of the eBottle. The given eBottle is not inserted as a nested eBottle.
Parameters:
[in] yb The eBottle whose eValues will be appended
References count(), and getPtr().
void eBottle::remove (const unsigned int i)
Removes the eValue at a certain position
Parameters:
[in] i The position of the eValue to remove
unsigned int eBottle::count () const
Access to the eBottle size
Returns:
The amount of eValues inside the eBottle (nested eBottles are considered as one eValue)
Referenced by append(), and copy().
unsigned int eBottle::size () const
Access to the eBottle size
Returns:
The amount of eValues inside the eBottle (nested eBottles are considered as one eValue)
Referenced by getBinarySize(), read(), and write().
eValue & eBottle::operator[] (const unsigned int i)
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
The eValue at the i position
eValue & eBottle::operator[] (const unsigned int i) const
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
The eValue at the i position
eValue & eBottle::get (const unsigned int i)
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
The eValue at the i position
eValue & eBottle::get (const unsigned int i) const
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
The eValue at the i position
eValue * eBottle::getPtr (const unsigned int i) const
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
A constant pointer to the eValue at the i position
Referenced by append(), copy(), and operator=().
eValue * eBottle::getPtr (const unsigned int i)
Access to the eBottle contents
Parameters:
[in] i A position inside the eBottle
Returns:
A pointer to the eValue at the i position
std::string eBottle::toString () const
Builds a string that represents all the contents of the eBottle
Returns:
The string representing the eBottle
void eBottle::fromString (const char * s)
Builds an eBottle from its string representation
Parameters:
[in] s A pointer to a null terminated char array representing an eBottle
Referenced by eBottle(), and fromString().
void eBottle::fromString (const std::string & s)
Builds an eBottle from its string representation
Parameters:
[in] s The string representing the eBottle
References fromString().
void eBottle::fromString (const ConstString & s)
Builds an eBottle from its string representation
Parameters:
[in] s The string representing the eBottle
References fromString().
void eBottle::fromBinary (const char * p, const int size)
Builds an eBottle from its binary representation
Parameters:
[in] p A pointer to the byte array with the binary representation
[in] size The size of the binary representation in bytes
Referenced by read().
const char *const eBottle::toBinary (int * size) const
Creates a binary representation of the eBottle
Parameters:
[out] size The size of the binary representation in bytes
Returns:
A constant pointer owned by the eBottle to the binary representation
Referenced by write().
void eBottle::toBinary (char * p) const
Creates a binary representation of the eBottle
Parameters:
[out] p A pointer to a zone of memory owned by the caller which is big enough to receive a copy of the binary representation of the eBottle. The size of the binary representation can be computed using eBottle::getBinarySize method.
unsigned int eBottle::getBinarySize () const
Computes the size of the binary representation of the eBottle
Returns:
The size in bytes of the binary representation of th eBottle.
See also:
toBinary
References size().
Referenced by write().
bool eBottle::read (ConnectionReader & connection) [virtual]
This function is inherited from Portable interface and is used in data transmission.
References clear(), fromBinary(), and size().
bool eBottle::write (ConnectionWriter & connection) [virtual]
This function is inherited from Portable interface and is used in data transmission.
References getBinarySize(), size(), and toBinary().
The documentation for this class was generated from the following files:
eBottle.h
eBottle.cc